using FluentAssertions;
using MediaBrowser.Plugins.AniMetadata.Configuration;
using MediaBrowser.Plugins.AniMetadata.Files;
using NUnit.Framework;

namespace MediaBrowser.Plugins.AniMetadata.Tests
{
    [TestFixture]
    public class PluginConfigurationTests
    {
        [Test]
        public void CanBeDeserialised()
        {
            var expected = new PluginConfiguration();

            var actual = new XmlSerialiser().Deserialise<PluginConfiguration>(
                @"<?xml version=""1.0"" encoding=""utf-16""?>
<PluginConfiguration xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <TitlePreference>Localized</TitlePreference>
  <MaxGenres>5</MaxGenres>
  <MoveExcessGenresToTags>true</MoveExcessGenresToTags>
  <AddAnimeGenre>true</AddAnimeGenre>
  <SeriesMappings>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>Name</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>Name</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>Name</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>Name</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>PremiereDate</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>PremiereDate</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>PremiereDate</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>PremiereDate</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>EndDate</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>EndDate</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>EndDate</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>CommunityRating</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>CommunityRating</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>CommunityRating</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>CommunityRating</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>Overview</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>Overview</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>Overview</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>Overview</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>Studios</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>Studios</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>Studios</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>Genres</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>Genres</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>Genres</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>Genres</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>Tags</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>Tags</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>Tags</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>Tags</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>People</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>People</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>People</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>AirDays</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>AirDays</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>AirDays</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>AirTime</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>AirTime</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>AirTime</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
  </SeriesMappings>
</PluginConfiguration>");

            actual.ShouldBeEquivalentTo(expected);
        }

        [Test]
        public void CanBeSerialised()
        {
            var configuration = new PluginConfiguration();

            var serialised = new XmlSerialiser().Serialise(configuration);

            serialised.Should()
                .Be(@"<?xml version=""1.0"" encoding=""utf-16""?>
<PluginConfiguration xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <TitlePreference>Localized</TitlePreference>
  <MaxGenres>5</MaxGenres>
  <MoveExcessGenresToTags>true</MoveExcessGenresToTags>
  <AddAnimeGenre>true</AddAnimeGenre>
  <SeriesMappings>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>Name</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>Name</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>Name</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>Name</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>PremiereDate</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>PremiereDate</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>PremiereDate</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>PremiereDate</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>EndDate</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>EndDate</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>EndDate</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>CommunityRating</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>CommunityRating</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>CommunityRating</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>CommunityRating</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>Overview</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>Overview</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>Overview</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>Overview</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>Studios</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>Studios</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>Studios</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>Genres</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>Genres</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>Genres</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>Genres</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>Tags</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>Tags</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>Tags</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>Tags</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>People</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>AniDB</SourceName>
          <TargetPropertyName>People</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>People</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>AirDays</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>AirDays</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>AirDays</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
    <PropertyMappingKeyCollection>
      <TargetPropertyName>AirTime</TargetPropertyName>
      <Mappings>
        <PropertyMappingKey>
          <SourceName>TvDB</SourceName>
          <TargetPropertyName>AirTime</TargetPropertyName>
        </PropertyMappingKey>
        <PropertyMappingKey>
          <SourceName>None</SourceName>
          <TargetPropertyName>AirTime</TargetPropertyName>
        </PropertyMappingKey>
      </Mappings>
    </PropertyMappingKeyCollection>
  </SeriesMappings>
</PluginConfiguration>");
        }
    }
}